### ISSUE TITLE
Reverse search does not work

### ISSUE THREAD

**Issue by certainlyakey** [xavi-/sublime-selectuntil#14]
It seems the reverse search with minus does not work... Is this the same minus that is located to the right of `0`? Stupid question but just in case... Should there be a space after minus? I tried to search this way: `-sum`, so that in `Lorem Ipsum is simply dummy text of the [cursor] printing` cursor would move after `sum`, but nothing happens and cursor doesn't move at all from initial position. 

I'm on Sublime Text 3083.

It's both with `"extend": false` and `"extend": true`.

**Comment by certainlyakey** [comment]
OK, I got it, reverse search works only with `-[...]` syntax. Maybe this should be made more clear in the panel caption.

**Comment by xavi-** [comment]
Yes, that's exactly right.  It requires the brackets because it's not too unusual in my experience to search by dashes.

It's definitely a usability issue.  Btw, if you hit <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>s</kbd> while the search panel is open, the search string will automatically reverse itself.
